### ISSUE TITLE
Science Being Lost Upon Disconnect

### ISSUE THREAD

**Issue by TwinDragon** [Caylis1397/Syncrio#9]
Much as I love this mod and all, but its becoming a bit of a problem as of late; especially so when I'm starting to lose upwards of 700+ science after going on expeditions to complete the tree. Example, I just finished a massive round of getting science from Eve, probably upwards of 2000 Science credit. That is now **gone** after I got disconnected from Syncrio. It seems that if you don't transmit anything, and you go on these long journeys, you are guaranteed to lose science. The data is still stored, but none of the values are ever kept. This happens if you disconnect normally, or through a random error. The server itself is hosted on a local Debian box I have and I have no connection issues to the box itself. I don't lose connection to DMP, only Syncrio. I took this blurb from the log file, not sure if it'll help:

> [16:54:09][DEBUG] : TwinShadow sent data type: PROGRESS_UPDATED
> [16:54:09][DEBUG] : TwinShadow sent data type: PROGRESS_UPDATED
> [16:54:09][INFO] : Client TwinShadow disconnected in ReceiveCallback, endpoint ::ffff:192.168.1.1:52363, error: EndRead failure (Connection reset by peer)
> [16:54:09][DEBUG] : Online players is now: 0, connected: 0
> [16:55:27][DEBUG] : Online players is now: 0, connected: 1
> [16:55:27][INFO] : New client connection from ::ffff:192.168.1.1:52681
> [16:55:27][INFO] : Client TwinShadow handshook successfully, version: v1.0.0.0-beta.3
> [16:55:27][DEBUG] : Online players is now: 1, connected: 1
> [16:55:27][DEBUG] : Sending TwinShadow to subspace 864
> [16:55:27][DEBUG] : TwinShadow acquired lock contract-spawn-Sync

Note, I am a little angry and did a minor rage quit of the game. I'll probably get back to it soon enough, but going back and forth from the Mun and Minmus does get a little old after a while. Which is why I took a trip to Eve to get started on it. But looks like I can't complete it if I can never bring any of that science back. (as transmitting data always cuts it by at least 60%, not worth it when most of the science I get there is 150+, and a couple being nearly 400)

**Comment by meyer9** [comment]
Should be fixed on my fork.

**Comment by TwinDragon** [comment]
Hm, alright. Only problem is I don't have a way to compile the code on Windows. Compiling on Windows is definitely not a specialty of mine.

**Comment by meyer9** [comment]
[syncrioclient.zip](https://github.com/Caylis1397/Syncrio/files/1405679/syncrioclient.zip)

[SyncrioServer.zip](https://github.com/Caylis1397/Syncrio/files/1405683/SyncrioServer.zip)

Here are the compiled versions. I think it would be cool to add automatic builds to the GitHub, but the developer doesn't seem active.

**Comment by TwinDragon** [comment]
Awesome, I'll try and get back to you on whether or not it works well. I did some local modding of my game for a few things, but it broke the info drive from B9, so another thing to fix. Not sure what caused that to happen..

**Comment by meyer9** [comment]
Yeah, let me know if it works for you. I tested it a couple times yesterday and it worked, but I haven't played extensively for a few days.

**Comment by Caylis1397** [comment]
Hello TwinDragon, I'm sorry that I did not see this bug report earlier. I'm going to look into merging meyer9's pull request that fixes this. Again sorry for not responding sooner.

**Comment by TwinDragon** [comment]
Oh, not a problem. Just reporting it so it can get fixed. I still haven't had a chance to test it since I have to remake some mod control files and other things I've been doing.
